apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app-container
        image: akash300/news-react:6
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: react-app-svc
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 32007
  selector:
    app: react-app
